# Grid間の距離 ( 実寸値 )
# AsymmetricCirclesGridの場合下記のような●の中心間距離( = 矢印 ) を入れる
# ●⇔●  ●  ●  ●  ●
# ⇕●　●　●　●　●　
# ●　●　●　●　●　●
# [ unit : mm ]
grid_interval: 40

# Gridの数
# SymmetricCirclesGrid, AsymmetricCirclesGrid の場合は Circle の数を指す
grid_num:            
  horizontal: 11
  vertical: 4
img:
  input_dir: "/home/hishida/01_Project/03_Toppan/Data/ForCalibration/きらきらロボモン①_temi0101"
  extension: "jpg"
output:
  file_name: calibration_param    # 求めたcalibration用paramterを書き出すファイルの名前

# SymmetricCirclesGrid, AsymmetricCirclesGrid の場合のみ使用
# circle (BLOB) の半径 [ unit : mm ]
circle_radius: 7.5