start_time: 29      # unit: second
end_time: 44       # unit: second
input_path: "/home/hishida/10_project_in_progress/016_ベローチェ/004_script/camera-calibration/sample/concatenated_video.avi"
output_dir: "/home/hishida/10_project_in_progress/016_ベローチェ/004_script/camera-calibration/sample/"