cut_flag: 1          # 1 -> Cut all frames, 0 -> Cut intervally
time:
  start_time: 20      # unit: second
  end_time: 70        # unit: second
number:
  output_sheets: 20   # unit: sheets
extension: "jpg"
input_path: "/home/hishida/10_project_in_progress/016_ベローチェ/004_script/camera-calibration/movie/video_20210525_11.avi"